In [1]:
import pandas as pd
df=pd.read_csv('TVShows_Netflix.csv')

In [2]:
df.head()

            Titles  Year Rating  IMDB_Rating Netflix_Availability
0     Breaking Bad  2008    18+          9.5                  Yes
1  Game of Thrones  2011    18+          9.3                   No
2   Rick and Morty  2013    18+          9.2                   No
3             Dark  2017    16+          8.8                  Yes
4  Stranger Things  2016    16+          8.8                  Yes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Titles                50 non-null     object
 1   Year                  50 non-null     int64
 2   Rating                50 non-null     object
 3   IMDB_Rating           50 non-null     float64
 4   Netflix_Availability  50 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.1+ KB

In [4]:
df.describe(include='all')

              Titles         Year Rating  IMDB_Rating Netflix_Availability
count             50    50.000000     50    50.000000                   50
unique            50          NaN      3          NaN                    2
top     Breaking Bad          NaN    18+          NaN                   No
freq               1          NaN     27          NaN                   31
mean             NaN  2009.900000    NaN     8.722000                  NaN
std              NaN     6.746881    NaN     0.358734                  NaN
min              NaN  1989.000000    NaN     8.000000                  NaN
25%              NaN  2005.250000    NaN     8.500000                  NaN
50%              NaN  2011.000000    NaN     8.700000                  NaN
75%              NaN  2015.000000    NaN     8.900000                  NaN
max              NaN  2019.000000    NaN     9.500000                  NaN

In [5]:
df.isnull().sum()

Titles                  0
Year                    0
Rating                  0
IMDB_Rating             0
Netflix_Availability    0
dtype: int64

In [6]:
df.columns=df.columns.str.lower()

In [7]:
df.columns

Index(['titles', 'year', 'rating', 'imdb_rating', 'netflix_availability'], dtype='object')

In [8]:
df=df.rename(columns={'rating':'age_rating'})

In [9]:
df.columns

Index(['titles', 'year', 'age_rating', 'imdb_rating', 'netflix_availability'], dtype='object')

In [10]:
df.head()

            titles  year age_rating  imdb_rating netflix_availability
0     Breaking Bad  2008        18+          9.5                  Yes
1  Game of Thrones  2011        18+          9.3                   No
2   Rick and Morty  2013        18+          9.2                   No
3             Dark  2017        16+          8.8                  Yes
4  Stranger Things  2016        16+          8.8                  Yes

In [11]:
# creat a column age_rating_tier
age_rating_map ={
    '7+':'Kids',
'16+':'Teens',
'18+':'Adults'
}
df['age_rating_tier']=df['age_rating'].map(age_rating_map)

In [12]:
df[['age_rating','age_rating_tier']].head(10)

  age_rating age_rating_tier
0        18+          Adults
1        18+          Adults
2        18+          Adults
3        16+           Teens
4        16+           Teens
5         7+            Kids
6        16+           Teens
7        18+          Adults
8        16+           Teens
9        16+           Teens

In [13]:
df.head(8)

,titles,year,age_rating,imdb_rating,netflix_availability,age_rating_tier
0,Breaking Bad,2008,18+,9.5,Yes,Adults
1,Game of Thrones,2011,18+,9.3,No,Adults
2,Rick and Morty,2013,18+,9.2,No,Adults
3,Dark,2017,16+,8.8,Yes,Teens
4,Stranger Things,2016,16+,8.8,Yes,Teens
5,Avatar: The Last Airbender,2005,7+,9.2,Yes,Kids
6,Sherlock,2010,16+,9.1,Yes,Teens
7,Chernobyl,2019,18+,9.4,No,Adults

In [14]:
df=df.rename(columns = {'year':'release_year'})

In [15]:
df.head()

,titles,release_year,age_rating,imdb_rating,netflix_availability,age_rating_tier
0,Breaking Bad,2008,18+,9.5,Yes,Adults
1,Game of Thrones,2011,18+,9.3,No,Adults
2,Rick and Morty,2013,18+,9.2,No,Adults
3,Dark,2017,16+,8.8,Yes,Teens
4,Stranger Things,2016,16+,8.8,Yes,Teens

In [16]:
# create a column release_era

bins=[0,1989,1999,2009,2019,2030]
labels=['Classic','90s','2000s','2010s','Modern']
df['release_era']=pd.cut(df['release_year'],bins=bins,labels=labels)

In [17]:
df.head(10)

,titles,release_year,age_rating,imdb_rating,netflix_availability,age_rating_tier,release_era
0,Breaking Bad,2008,18+,9.5,Yes,Adults,2000s
1,Game of Thrones,2011,18+,9.3,No,Adults,2010s
2,Rick and Morty,2013,18+,9.2,No,Adults,2010s
3,Dark,2017,16+,8.8,Yes,Teens,2010s
4,Stranger Things,2016,16+,8.8,Yes,Teens,2010s
5,Avatar: The Last Airbender,2005,7+,9.2,Yes,Kids,2000s
6,Sherlock,2010,16+,9.1,Yes,Teens,2010s
7,Chernobyl,2019,18+,9.4,No,Adults,2010s
8,Friends,1994,16+,8.9,No,Teens,90s
9,The Office,2005,16+,8.9,Yes,Teens,2000s

In [18]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\sabrin\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\sabrin\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\sabrin\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sabrin\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from sqlalchemy import create_engine
# connect to postgresql

username = "postgres"
password = "87211"
host = "localhost"
port = "5432"
database = "TVShows_Netflix"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "TVShows"
df.to_sql( table_name,engine, if_exists="replace" , index = False) 

print (f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'TVShows' in database 'TVShows_Netflix'.